name: CI/CD to S3

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies & Build Project
        run: |

          cd frontend/ && ls
          npm i
          npm run build


  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Upload and Delete Files from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

        run: |
          aws s3 sync /home/runner/work/eum/eum/frontend/dist s3://megather-front-develop/ --delete

        if: success()  # Only run deployment if the build job was successful

#aws s3 sync path/to/your/local/files s3://your-s3-bucket-name/ --delete

#   steps:
 #     - name: Upload Files to S3
 #       uses: jakejarvis/s3-sync-action@v0.5.1
 #       with:
 #         args: --acl public-read --follow-symlinks --delete
 #       env:
 #         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
 #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 #         AWS_REGION: ${{ secrets.AWS_REGION }}
 #       if: success()  # Only run deployment if the build job was successful
